### PR TITLE
Updates to apb init and docs

### PR DESCRIPTION
**Pull request by cfchase**
Update init to create new binding.
Update apb command for verbose.
Update getting started docs.

### CODE REVIEW

**Comment by cfchase** [comment]
Github looks like it's hiding the getting_started.md diff by default.

**Comment by cfchase** [comment]
[(8) Hide APB binding encoding in a module[asb][apbs]](https://trello.com/c/Y5YouiPB/231-8-hide-apb-binding-encoding-in-a-moduleasbapbs)

**Comment by cfchase** [comment]
[Update APB Tooling and docs with more improvements](https://trello.com/c/07CS00Zl/393-update-apb-tooling-and-docs-with-more-improvements)

**Comment by dymurray** [comment]
ACK

**Pull request merged**
