### PR TITLE
Add GPL V2 license for APB repo

### PR DESCRIPTION
**Pull request by dymurray**

### CODE REVIEW

**Comment by cfchase** [comment]
ACK

**Comment by rthallisey** [comment]
@dymurray  Would this mean that any APB written carries the GPL licence?  If so, then projects won't want to keep them in their repos because I think it contaminates that project's licence?

**Comment by dymurray** [comment]
@rthallisey From my understanding it would not mean that any APB written using this program carries the GPL license by default. @jmrodri can you comment?

**Comment by rthallisey** [comment]
https://opensource.stackexchange.com/questions/2501/does-using-a-gplv2-code-generator-force-my-project-to-be-similarly-licensed

>According to the GPL FAQ the output of a GPL program is not licensed under the GNU GPL, unless it copies substantial parts of source code into the output which are complex enough to fall under copyright:

    Q:In what cases is the output of a GPL program covered by the GPL too?

    A: Only when the program copies part of itself into the output.
>

**Comment by rthallisey** [comment]
I don't think we're copying substantial parts of source code.  So I think it should be ok.

**Comment by dymurray** [comment]
@rthallisey Yeah agreed, thanks for the source.

**Pull request merged**
