### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by jmrodri**
Trying to fix travis linter checks.

### CODE REVIEW

**Review by fabianvf — APPROVED** [review]
LGTM, though personally I much prefer removing the 79 character line length requirement to formatting code around it

**Comment by fabianvf** [comment]
Also I think if you pip install kubernetes before running Python setup.py install it'll be happy, probably an issue of bdist vs sdist or something stupid like that

**Comment by dymurray** [comment]
Yeah agree with Fabian I hate the 79 char limit but big +1 for fixing travis.

**Review by dymurray — APPROVED** [review]
Thanks Jesus!

**Pull request merged**
