### PR TITLE
Update docs for bundle spec bump to 1.1 to support dependencies

### PR DESCRIPTION
**Pull request by philipgough**
Relates to:
* https://github.com/openshift/ansible-service-broker/issues/859
* https://github.com/openshift/ansible-service-broker/pull/928
* https://github.com/automationbroker/bundle-lib/pull/70

@dymurray anything else you would like to see here or is this all from docs side?

### CODE REVIEW

**Review by dymurray — APPROVED** [review]

**Comment by dymurray** [comment]
Looks great thanks @PhilipGough

**Comment by philipgough** [comment]
@dymurray Hey, will we close this? I assume it is outdated at this stage?

**Comment by djzager** [comment]
My apologies that I missed this and it wasn't handled more timely.

Believe it or not. APBs have not changed very much, if at all, since this PR was submitted. It still looks good to me and my temptation is to accept the change. What are your thoughts @PhilipGough ?

**Comment by philipgough** [comment]
@djzager - No problem. My thoughts are I haven't been involved in the project for some time and I wouldn't be comfortable merging this without retesting. Leave it with me and I'll rest after the break. We can discuss then based on results. How does that sound?

**Pull request closed without merging**
