### PR TITLE
Add the ability to create most of a serviceinstance template

### PR DESCRIPTION
**Pull request by rthallisey**
Most of the serviceinstance template can be created based off of
apb.yml.  Generate a nearly complete template and let the user
fill in the parameter values.

### CODE REVIEW

**Review by jmrodri — APPROVED** [review]
ACK

**Comment by rthallisey** [comment]
Testing
-----
```bash
[rhallisey@rhev-i16c-04 mediawiki123-apb]$ apb serviceinstance
Only displaying vars from the 'default' plan.
[rhallisey@rhev-i16c-04 mediawiki123-apb]$ cat mediawiki123-apb.yaml 
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mediawiki123-apb
spec:
  clusterServiceClassExternalName: dh-mediawiki123-apb
  clusterServicePlanExternalName: (Plans->|default)
  parameters:
    mediawiki_admin_pass: ansibleplaybookbundle
    mediawiki_admin_user: ansibleplaybookbundle
    mediawiki_db_schema: ansibleplaybookbundle
    mediawiki_site_lang: ansibleplaybookbundle
    mediawiki_site_name: ansibleplaybookbundle
```
Replace ```ansibleplaybookbundle``` with a valid input and replace ```clusterServicePlanExternalName: (Plans->|default)``` with a valid clusterserviceplan.  The plans will be in ```(Plans->|default|prod|v2)``` format. Create the serviceinstance ```oc create -f mediawiki123-apb.yaml``` to launch the apb through the catalog.

**Comment by rthallisey** [comment]
@dymurray are you ok with this PR?

**Comment by rthallisey** [comment]
@dymurray any comments before I merge?

**Comment by rthallisey** [comment]
[Improve interaction with the Service Catalog through the cli](https://trello.com/c/TMCsyatm/600-improve-interaction-with-the-service-catalog-through-the-cli)

**Review by dymurray — APPROVED** [review]

**Pull request merged**
