### PR TITLE
Remove devel directory

### PR DESCRIPTION
**Pull request by rthallisey**
https://github.com/fusor/ansible-playbook-bundle/issues/2

### CODE REVIEW

**Comment by jmrodri** [comment]
What were these files for? Are they an old devel environment? @dymurray

**Comment by jmrodri** [comment]
@dymurray if you don't need devel dir. Feel free to merge this pr.

**Review by jmrodri — APPROVED** [review]
ACK looks go to me, as long as @dymurray no longer needs these.

**Comment by dymurray** [comment]
ACK

**Pull request merged**
