### PR TITLE
Better error handling when logged out of the cluster

### PR DESCRIPTION
**Pull request by dymurray**
Fixes issue #155

### CODE REVIEW

**Review by rthallisey — APPROVED** [review]

**Comment by rthallisey** [comment]
@dymurray you want to use one of these key words so that git closes the issue after this merges: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by dymurray** [comment]
Fixes #155

**Comment by dymurray** [comment]
Thanks @rthallisey

**Comment by djwhatle** [comment]
dymurray++

**Pull request merged**
