### PR TITLE
Fixes #102 - Wrap apb in a docker image

### LINKED ISSUE #102: wrap apb tool in docker image
Wonder if creating an apb docker image would be a good way to go here?
Setting up python and the virtural env took a while for different reasons. Where as being able to do ``` docker run fusor/apb init org/image ``` might provide a better option for those not familiar with python ?

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by maleck13** [comment]
@jmontleon tried the latest image locally and worked great 👍

**Comment by maleck13** [comment]
@jmontleon actually hit in issue when doing a build.
```
Exception occurred! Error while fetching server API version: ('Connection aborted.', error(2, 'No such file or directory'))
```
perhaps because it is doing a docker build inside docker a docker image?
Is the docker build doing anything special? Or just a regular docker build?
```
docker build -t <org/repo>
```

**Comment by jmontleon** [comment]
@maleck13 docker build -t as far as I know. @dymurray could probably say for certain.

You can actually mount the docker.sock file in the container to get apb build to work. The problem I am having is that I know have to run the container as root and with privileged to get it to work, which goes a little beyond what an alias can do.

```
function apb() {
  if [[  "$@" == "build"* ]]; then
    docker run --rm --privileged -v $(pwd):/mnt:z -v /var/run/docker.sock:/var/run/docker.sock ansibleplaybookbundle/apb $@
  else
    docker run --rm -u $(id -u) -v $(pwd):/mnt:z ansibleplaybookbundle/apb $@
  fi
}
```

```
$ apb init foo/bar
Initializing /mnt/bar for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/bar
Please run *apb prepare* inside of this directory after editing files.
$ cd bar
$ apb prepare
Finished writing dockerfile.
$ apb build
Finished writing dockerfile.
Building APB using tag: [foo/bar]
Successfully built APB image: foo/bar
```

**Comment by maleck13** [comment]
@jmontleon If it is just doing a docker build. I am happy to do that outside of the tool

**Comment by jmontleon** [comment]
I was able to get it to work again with alias/atomic run, but the alias is a bit different and I had to add a wrapper script:

Dockerfile:
```
FROM centos:7

RUN curl https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker-latest/repo/epel-7/group_ansible-service-broker-ansible-service-broker-latest-epel-7.repo -o /etc/yum.repos.d/asb.repo
RUN yum -y install epel-release centos-release-openshift-origin && yum -y install apb sudo origin-clients && yum clean all

WORKDIR /mnt

RUN echo "ALL ALL=NOPASSWD: ALL" > /etc/sudoers.d/usermod
RUN chmod 666 /etc/passwd
COPY apb-wrapper /usr/local/bin/apb-wrapper
RUN chmod +x /usr/local/bin/apb-wrapper

ENTRYPOINT ["apb-wrapper"]
CMD ["-h"]

LABEL RUN docker run --privileged --rm -v \${PWD}:/mnt -v \$HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u \${SUDO_UID} \${IMAGE}
```

apb-wrapper:
```
#!/bin/bash

if [ -f /opt/apb/bin/activate ] ; then
 source /opt/apb/bin/activate
fi

echo "apb:x:$UID:$UID:apb:/home/apb:/bin/bash" >> /etc/passwd
sudo groupadd apb -g $UID
sudo usermod -a -G apb apb

gid=$(stat -c '%g' /var/run/docker.sock)
if [[ "0" == "$gid" ]]; then
  group=root
else
  group=docker
  sudo groupadd $group -g $gid
fi
sudo usermod -a -G $group apb

command="apb $@"
sg $group -c "$command"
```

```
alias apb='docker run --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID ansibleplaybookbundle/apb'
```

@dymurray how do you feel about this?

**Comment by jmontleon** [comment]
@dymurray I just updated the comment above. I think it has everything it needs to work with oc and docker now.

I updated the label for atomic run as well; Downside is we need --privileged to connect to the docker socket (this is expected) and atomic run outputs an obnoxious multi-line warning for each command. But it does work.

```

$ atomic run ansibleplaybookbundle/apb init foo/bar
docker run --privileged --rm -v /home/jmontleo/Desktop:/mnt -v /home/jmontleo/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u 13693 ansibleplaybookbundle/apb init foo/bar
<snip>
Initializing /mnt/bar for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/bar
Please run *apb prepare* inside of this directory after editing files.

$ cd bar

$ atomic run ansibleplaybookbundle/apb prepare
docker run --privileged --rm -v /home/jmontleo/Desktop/bar:/mnt -v /home/jmontleo/.kube:/.kube -v/var/run/docker.sock:/var/run/docker.sock -u 13693 ansibleplaybookbundle/apb prepare
<snip>
Finished writing dockerfile.

$ atomic run ansibleplaybookbundle/apb build
docker run --privileged --rm -v /home/jmontleo/Desktop/bar:/mnt -v /home/jmontleo/.kube:/.kube -v/var/run/docker.sock:/var/run/docker.sock -u 13693 ansibleplaybookbundle/apb build
<snip>
Finished writing dockerfile.
Building APB using tag: [foo/bar]
Successfully built APB image: foo/bar
```
or:

```
$ alias apb='docker run --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID ansibleplaybookbundle/apb'

$ apb init foo/bar
Initializing /mnt/bar for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/bar
Please run *apb prepare* inside of this directory after editing files.

$ cd bar

$ apb prepare
Finished writing dockerfile.

$ apb build
Finished writing dockerfile.
Building APB using tag: [foo/bar]
Successfully built APB image: foo/bar
```

I tested oc in the container as well and it seems to work, so maybe the endpoint stuff will work too. I will be curious to hear back.

**Comment by dymurray** [comment]
I was able to run every command except 'apb push' because it expects apb.yml in its current directory. I'm trying to find a workaround.

**Comment by dymurray** [comment]
[dymurray@dymurray-desktop linux]$ apb push
Exception occurred! ERROR: Spec file: [ /mnt/apb.yml ] not found

**Comment by jmontleon** [comment]
Is apb.yml in the current working directory when you run apb push?

```
[jmontleo@jmontleo Desktop]$ apb init jmontleon/foo
$ apb init jmontleon/foo
Initializing /mnt/foo for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/foo
Please run *apb prepare* inside of this directory after editing files.
$ apb push 
Exception occurred! ERROR: Spec file: [ /mnt/apb.yml ] not found
$ cd foo/
$ apb push
Exception occurred! Could not find route to ansible-service-broker. Use --broker or log into the cluster using "oc login"
```

**Comment by jmontleon** [comment]
@dymurray  is apb.yml in the current working directory when you run apb push?

$PWD is mounted, so whatever directory you're working in is available in the container at /mnt, if you're using atomic run or using the alias like so:

`alias apb='docker run --privileged -v $PWD:/mnt -v $HOME/.kube:/.kube -v /var/run/docker.sock:/var/run/docker.sock -u $UID ansibleplaybookbundle/apb'`



```
[jmontleo@jmontleo Desktop]$ apb init jmontleon/foo
$ apb init jmontleon/foo
Initializing /mnt/foo for an APB.
Generating playbook files
Successfully initialized project directory at: /mnt/foo
Please run *apb prepare* inside of this directory after editing files.
$ apb push 
Exception occurred! ERROR: Spec file: [ /mnt/apb.yml ] not found
$ cd foo/
$ apb push
Exception occurred! Could not find route to ansible-service-broker. Use --broker or log into the cluster using "oc login"
```

once i actually had a broker running with basic auth off
```
$ apb push
Successfully added APB to Ansible Service Broker
```

Edit: nm, saw your response on irc.

**Comment by dymurray** [comment]
@jmontleon Yeah sorry the testing problem was on my end. I can confirm this works for me. ACK.

**Pull request merged**
